name: pycmtensor-dev
dependencies:
    - python==3.10
    - mkl-service
    - conda-forge::cxx-compiler

# linux / macos
# conda install mkl-service conda-forge::cxx-compiler
# conda activate pycmtensor-dev
# pip install poetry
# poetry install