name: pycmtensor-dev
dependencies:
    - python==3.9.7
    - pip
    - git
    - numpy
    - mkl
    - conda-forge::libpython
    - conda-forge::cxx-compiler
    - conda-forge::libblas
# conda install nb_conda_kernels -n base
# conda env create -f environment.yml, or
# conda env update -n base -f environment.yml
# pip install pycmtensor -U

# windows 
# conda install blas mkl-service conda-forge::libpython conda-forge::cxx-compiler
# linux 
# conda install blas mkl-service conda-forge::cxx-compiler