name: pycmtensor-dev
dependencies:
    - python==3.9.7
    - pip
    - git
    - numpy
    - mkl
    - conda-forge::libpython
    - conda-forge::cxx-compiler
    - conda-forge::m2w64-toolchain
    - conda-forge::libblas

# windows 
# conda install blas mkl-service conda-forge::libpython conda-forge::cxx-compiler conda-forge::m2w64-toolchain

# linux 
# conda install blas mkl-service conda-forge::cxx-compiler