name: pycmtensor-dev
dependencies:
    - python==3.9.7
    - pip
    - git
    - numpy=1.21.5
    - mkl>2021.0.0,<2022.0.0
    - conda-forge::libpython
    - conda-forge::m2w64-toolchain
    - conda-forge::cxx-compiler
    - conda-forge::libblas
# conda install nb_conda_kernels
# conda env create -f environment.yml, or
# conda env update -n base -f environment.yml
# pip install git+https://github.com/mwong009/pycmtensor.git -U

# windows -c anaconda -c conda-forge pip git numpy libpython libblas mkl-service
# linux -c anaconda -c conda-forge pip git numpy libblas mkl-service