name: pycmtensor-dev
channels:
    - conda-forge
    - defaults
dependencies:
    # core dependencies
    - python>=3.9,<3.13
    - aesara=2.9.3
    - numpy<1.26.0
    - scipy<1.12.0
    - pandas<2.1.0
    - seaborn<0.14.0
    - watermark=2.4.3
    
    # testing
    - pytest>=7.4.3


# remove any old environment
# conda env remove -n pycmtensor-dev

# install the environment
# conda env create -f environment.yml && conda activate pycmtensor-dev

# development
# conda install git ipykernel poetry
# poetry install --with docs,test,lint