name: pycmtensor-dev
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.11
    - aesara

# conda env create -f environment.yml
# conda activate pycmtensor-dev
# python -m pip install --upgrade pip
# pip cache purge
# pip install poetry
# poetry update
# poetry install --with=dev,test,doc