name: pytensor-dev
channels:
    - conda-forge
    - defaults
dependencies:
    # core dependencies
    - python>=3.9,<3.13
    - pytensor<2.27.0
    - scipy<1.15.0
    - pandas<2.3.0
    - seaborn<0.14.0
    - scikit-learn<1.6.0
    
    # testing
    - pytest>=7.4.3


# remove any old environment
# conda env remove -n pytensor-dev -y

# navigate to this directory and install the environment
# conda env create -n pytensor-dev && conda activate pytensor-dev

# development
# conda install git ipykernel poetry
# poetry install --with docs,test,lint