name: pycmtensor-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9.7
  - pip>=21.2.4
  - git>=2.34.1
  - cxx-compiler==1.3.0
  - m2w64-toolchain==5.3.0
  - mkl==2021.4.0
  - mkl-service==2.4.0
  - ipykernel>=6.4.1
  - libblas>=3.9.0
  - libpython>=2.1
  
# conda install nb_conda_kernels
# conda env create -f environment.yml
# conda activate pycmtensor-dev
# pip install . , or
# pip install git+githttps://github.com/mwong009/pycmtensor.git
# conda remove --name pycmtensor-dev --all