name: pycmtensor
channels:
    - conda-forge
    - defaults
dependencies:
    # core dependencies
    - python<3.12
    - aesara=2.9.3
    - numpy=1.25.2
    - scipy=1.13.1
    - pandas=1.5.3
    - seaborn=0.12.2
    
    # testing
    - pytest>=7.4.3


# remove any old environment
# conda env remove -n pycmtensor

# install the environment
# conda env create && conda activate pycmtensor

# development
# conda install -c conda-forge ipykernel pytest-cov black isort commitizen pre-commit

# documentation
# conda install -c conda-forge mkdocs mkdocs-material mkdocstrings pymdown-extensions mkdocstrings-python mknotebooks