name: pycmtensor-dev
dependencies:
    - python==3.10
    - mkl-service
    - conda-forge::cxx-compiler
    - conda-forge::m2w64-toolchain

# windows 
# conda install mkl-service conda-forge::cxx-compiler conda-forge::m2w64-toolchain -y
# conda activate pycmtensor-dev
# pip install poetry
# poetry install -E dev