name: pycmtensor-dev
dependencies:
    - python==3.9.12
    - mkl-service
    - Clang

# macos
# conda install mkl-service Clang
# conda activate pycmtensor-dev
# pip install poetry
# poetry install -E dev