name: pycmtensor-dev
dependencies:
    - python==3.10
    - mkl-service
    - conda-forge::cxx-compiler
    - conda-forge::m2w64-toolchain

# windows 
# conda env create -f .\environment_windows.yml
# conda activate pycmtensor-dev
# pip install poetry
# poetry update
# poetry install -E dev