site_name: PyCMTensor - Documentation

nav:
  - Home: index.md
  - Getting started: 
    - Introduction: getting_started/index.md
    - Installation: getting_started/installation.md
    - Overview: getting_started/overview.md
    - Troubleshooting & tips: getting_started/troubleshooting.md
  - Examples: 
    - Multnomial logit: examples/mnl.ipynb
  - User guide:
    - User guide: user_guide/index.md
    - Configuration: user_guide/configuration.md
  - Developer guide:
    - Developer guide: developer_guide/index.md
    - API reference: 
      - API reference: developer_guide/api/index.md
      - __init__: developer_guide/api/__init__.md
      - config: developer_guide/api/config.md
      - dataset: developer_guide/api/dataset.md
      - expressions: developer_guide/api/expressions.md
      - functions: developer_guide/api/functions.md
      - logger: developer_guide/api/logger.md
      - models: 
        - basic: developer_guide/api/models/basic.md
        - MNL: developer_guide/api/models/MNL.md
      - optimizers: developer_guide/api/optimizers.md
      - results: developer_guide/api/results.md
      - scheduler: developer_guide/api/scheduler.md
      - statistics: developer_guide/api/statistics.md
  - About:
    - Contributing: about/contributing.md
    - Release notes: about/release_notes.md
    - Licence: about/licence.md
    - Citation: about/citation.md

theme:
  name: material
  palette:
    primary: teal
    accent: teal
    scheme: default
  favicon: assets/img/favicon.ico
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - content.code.copy
    - navigation.top

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mwong009/pycmtensor

repo_url: https://github.com/mwong009/pycmtensor

plugins:
  - search
  - mknotebooks:
      execute: false
      enable_default_pandas_dataframe_styling: false
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: false 
            merge_init_into_class: true
            show_symbol_type_heading: true
            separate_signature: false
            group_by_category: true

markdown_extensions:
  - admonition
  - fenced_code
  - codehilite:
      guess_lang: False
      linenums: False
      use_pygments: False
  - footnotes
  - pymdownx.arithmatex:
      generic: True
  - pymdownx.b64
  - pymdownx.betterem
  - pymdownx.blocks.admonition
  - pymdownx.blocks.definition
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.escapeall
  - pymdownx.extra
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.pathconverter
  - pymdownx.progressbar
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.striphtml
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: True
      clickable_checkbox: False
  - pymdownx.tilde
  - toc:
      permalink: True

extra_css:
  - assets/css/extra.css

extra_javascript:
  - assets/js/extra.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
