name: pycmtensor-dev
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.11
    - mkl-service
    - gcc_linux-64
    - gxx_linux-64
    - blas

# linux
# conda env create -f environment_linux.yml
# conda activate pycmtensor-dev
# python -m pip install --upgrade pip
# pip cache clear
# pip install poetry
# poetry update
# poetry install -E dev