name: pycmtensor-dev
dependencies:
    - python=3.11
    - mkl-service
    - conda-forge::cxx-compiler

# linux
# conda install mkl-service conda-forge::cxx-compiler
# conda activate pycmtensor-dev
# pip install poetry
# poetry install -E dev