name: pycmtensor-dev
dependencies:
    - python=3.11
    - mkl-service
    - conda-forge::cxx-compiler
    - conda-forge::m2w64-toolchain

# windows 
# conda env create -f .\environment_windows.yml
# conda activate pycmtensor-dev
# python -m pip install --upgrade pip
# pip install poetry
# poetry update
# poetry install -E dev