name: pycmtensor-dev
dependencies:
    - python=3.11
    - mkl-service
    - Clang

# macos
# conda install mkl-service Clang
# conda activate pycmtensor-dev
# conda install poetry
# poetry install -E dev