# This workflow will bump the version of the package and publish it to PyPI

name: Bump and publish

on: 
  workflow_dispatch:
  # push:
  #   branches:
  #     - master

jobs:
  bump_version:
    if: ${{ !startsWith(github.event.head_commit.message, 'bump:') }}
    strategy:
      matrix:
        python-version: ["3.11"]
        poetry-version: ["1.5.1"]
    runs-on: "ubuntu-latest"
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog_increment_filename: body.md
      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "body.md"
          tag_name: v${{ env.REVISION }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # deploy step
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Publish to PyPI
        run: |
          poetry config pypi-token.pypi "${{ secrets.PYPI_API_KEY }}"
          poetry publish --build
    
    
    
