name: Lint

on: pull_request

jobs:
  black:
    runs-on: [self-hosted, ARM64, Linux]
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          src: "."
          version: "23.11.0"

  isort:
    runs-on: [self-hosted, ARM64, Linux]
    steps:
      - uses: actions/checkout@v3
      - uses: isort/isort-action@v1
