name: Tests
on:
  pull_request:
    branches:
      - master

jobs:
  build-install:
    name: build-install
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ['3.9', '3.10']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Display Python version
      run: python --version
    
    - name: Add conda to path (Bash)
      run: |
        echo "$CONDA/condabin" >> $GITHUB_PATH
        echo "$CONDA/Library/bin" >> $GITHUB_PATH
        echo "CONDA_PREFIX=$CONDA" >> $GITHUB_ENV
      shell: bash
    
    - name: Install conda dependencies (Windows)  
      if: matrix.os == 'windows-latest'
      run: |
        conda install -c conda-forge libpython libblas m2w64-toolchain mkl-service numpy

    - name: Install conda dependencies (Linux)  
      if: matrix.os != 'windows-latest'
      run: |
        conda install mkl-service
    
    - name: Install package dependencies
      run: |
        pip install poetry
        poetry install
        poetry run python -c "import pycmtensor as cmt; print(cmt.__version__)"
    
    - name: Show contents of .aesararc
      run: |
        cat ~/.aesararc
      shell: bash
    
    - name: Test with pytest (Linux)
      if: matrix.os != 'windows-latest'
      run: |
        poetry run pytest
      
    - name: Test with pytest (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        poetry run pytest