name: run pytest
on:
  pull_request:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.*
    - name: Add conda to path
      run: |
        echo "$CONDA\condabin" >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
        conda init powershell
    - name: install poetry
      run: |
        pip install poetry
    - name: Install dependencies
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest
