name: poetry run pytest
on:
  pull_request:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.7
    - name: Install dependencies
      run: |
        conda env update -n base -f environment.yml
        pip install poetry
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest
