# This workflow will upload a Python Package using Poetry when a release is created
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload python package to PyPI

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.12'
    - name: Python Poetry Action
      uses: abatilo/actions-poetry@v2.1.3
    - name: Publish to PyPI
      run: |
        poetry config pypi-token.pypi "${{ secrets.PYPI_API_KEY }}"
        poetry publish --build
