name: Tests
on:
  pull_request:
    branches:
      - master

jobs:
  build-install-windows:
    name: build-install
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Display Python version
      run: python --version
    
    - name: Add conda to path (Bash)
      run: |
        echo "$CONDA/condabin" >> $GITHUB_PATH
        echo "$CONDA/Library/bin" >> $GITHUB_PATH
        echo "CONDA_PREFIX=$CONDA" >> $GITHUB_ENV
      shell: bash
    
    - name: Install conda dependencies
      run: |
        conda install blas mkl-service conda-forge::libpython conda-forge::cxx-compiler
    
    - name: Install package dependencies
      run: |
        pip install poetry
        poetry install
        poetry run python -c "import pycmtensor as cmt; print(cmt.__version__)"
    
    - name: Show contents of .aesararc
      run: |
        python -c "import sys; print(sys.platform)"
        cat ~/.aesararc
      shell: bash
      
    - name: Test with pytest
      run: |
        poetry run pytest

  build-install-linux:
    name: build-install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Display Python version
      run: python --version
    
    - name: Add conda to path (Bash)
      run: |
        echo "$CONDA/condabin" >> $GITHUB_PATH
        echo "$CONDA/Library/bin" >> $GITHUB_PATH
        echo "CONDA_PREFIX=$CONDA" >> $GITHUB_ENV
      shell: bash

    - name: Install conda dependencies 
      run: |
        conda install blas mkl-service conda-forge::cxx-compiler
    
    - name: Install package dependencies
      run: |
        pip install poetry
        poetry install
        poetry run python -c "import pycmtensor as cmt; print(cmt.__version__)"
    
    - name: Show contents of .aesararc
      run: |
        python -c "import sys; print(sys.platform)"
        cat ~/.aesararc
      shell: bash
    
    - name: Test with pytest
      run: |
        poetry run pytest
      

    - name: Upload coverage to codecov.io
      if: |
        matrix.python-version == '3.9'
      uses: codecov/codecov-action@v2
      with:
        files: coverage.xml
        path_to_write_report: ./coverage/codecov_report.txt