name: Tests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - "**-beta"

jobs:
  pycmtensor-test:
    name: (${{ matrix.python-version }}, ${{ matrix.os }})
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.11"]
    
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          auto-activate-base: false
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          
      - name: Display Conda packages
        run: |
          conda info
          conda list
      
      - name: Install pytest suite
        run: |
          conda install pytest pytest-cov
        
      - name: Xcode check (macos)
        if: matrix.os == 'macos-latest'
        run: |
          clang --version
          xcrun --show-sdk-path
      
      - name: Test pycmtensor import
        run: |
          python -c "import pycmtensor as cmt; print(cmt.__version__)"
          cat ~/.aesararc

      - name: Show Aesara config
        run: |
          python -c "import aesara; print(aesara.config.blas__ldflags)"
          python -c "import aesara; print(aesara.config.gcc__cxxflags)"

      - name: Main test
        run: pytest

      # - name: Upload coverage to codecov.io
      #   if: (matrix.os == 'ubuntu-latest') && (matrix.python-version == '3.11')
      #   uses: codecov/codecov-action@v3
      #   with:
      #     files: coverage.xml
  
  pycmtensor-arm64:
    name: (3.11, arm64)
    runs-on: [self-hosted, ARM64, Linux]
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          auto-activate-base: false
          environment-file: environment.yml
          python-version: 3.11
      
      - name: Install pytest suite
        run: conda install pytest pytest-cov
      
      - name: Main test
        run: pytest
      
      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
